name: 'Verify Lane In Consumer'
description: 'Create a new Bit lane for each new Git branch'
branding:
  icon: 'award'
  color: 'purple'
inputs:
  package-manager:
    description: 'The package manager to use for dependency installation'
    required: false
    default: 'npm'
  project-dir:
    description: 'The path to the consumer project'
    required: false
    default: './'
  lane-id:
    description: 'The ID of the Bit lane to sync from in the format: org.scope/lane'
    required: true
  test-command:
    description: 'The command to run the tests'
    required: false
    default: 'npm test'
  skip-push:
    description: 'Skip commit push (for testing)'
    required: false
  use-overrides:
    description: 'Add dependencies from lane to the package.json "overrides" property'
runs:
  using: 'node20'
  main: 'dist/index.js'
