name: 'Lane in Consumer Validation'
description: 'Create a new Bit lane for each new Git branch'
branding:
  icon: 'git-merge'
  color: 'purple'
inputs:
  package-manager:
    description: 'The package manager to use for dependency installation'
    required: false
    default: 'npm'
  project-dir:
    description: 'The path to the consumer project'
    required: false
    default: './'
  lane-id:
    description: 'The ID of the Bit lane to sync from in the format: org.scope/lane'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
