name: 'Lane in Consumer Validation'
description: 'Create a new Bit lane for each new Git branch'
branding:
  icon: 'git-merge'
  color: 'purple'
inputs:
  package-manager:
    description: 'The package manager to use for dependency installation'
    required: false
    default: 'npm'
  ws-dir:
    description: 'The path to the workspace'
    required: false
    default: './'
  lane-name:
    description: 'The name of the Bit lane to sync from in the format: org.scope/lane'
    required: true
  branch-name:
    description: 'The destination Git branch name where the updates are sync to'
    required: false
  skip-push:
    description: 'Skip commit push (for testing)'
    required: false
  skip-ci:
    description: 'Remove adding [skip-ci] to the .bitmap file commit message'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'initialize a temporary bit workspace'
      shell: bash
      run: mkdir -p "${RUNNER_TEMP}/bit-ws"
    - name: 'run install components from lane'
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        RUNNER_TEMP: ${{ runner.temp }}
