name: Test Verify Lane In Consumer
on:
  workflow_dispatch:
    inputs:
      lane-id:
        description: "The ID of the lane to install from in the format: org.scope/lane"
        required: true
        default: ""
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@v2
        with:
          skip-install: "true"
      - name: Verify Lane In Consumer
        uses: bit-tasks/verify-lane-in-consumer@master
        with:
          lane-id: ${{ github.event.inputs.lane-id }}
          project-dir: 'test-data'
          package-manager: 'npm'
